---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - testapp.github.com
  resources:
  - whatevers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - testapp.github.com
  resources:
  - whatevers/finalizers
  verbs:
  - update
- apiGroups:
  - testapp.github.com
  resources:
  - whatevers/status
  verbs:
  - get
  - patch
  - update
