# permissions for end users to edit whatevers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: whatever-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: operator-test
    app.kubernetes.io/part-of: operator-test
    app.kubernetes.io/managed-by: kustomize
  name: whatever-editor-role
rules:
- apiGroups:
  - testapp.github.com
  resources:
  - whatevers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - testapp.github.com
  resources:
  - whatevers/status
  verbs:
  - get
