# permissions for end users to view whatevers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: whatever-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: operator-test
    app.kubernetes.io/part-of: operator-test
    app.kubernetes.io/managed-by: kustomize
  name: whatever-viewer-role
rules:
- apiGroups:
  - testapp.github.com
  resources:
  - whatevers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - testapp.github.com
  resources:
  - whatevers/status
  verbs:
  - get
